### ISSUE TITLE
Ajouter des liens vers la ressource principale

### ISSUE THREAD

**Issue by martinsam** [cleverage/accessibility-steps#2]
Lorsqu'on souhaite contribuer c'est assez complexe en l'état.
Example : 
" https://github.com/cleverage/accessibility-steps/blob/master/accessibility-first-step/en/16%20-%20When%20you%20provide%20a%20h3%20element%2C%20do%20not%20leave%20it%20empty.md" 

Comment je trouve l'objectif , la solution technique  à traduire ? 

Deux solutions pour simplifier le travail de traduction :
- Soit afficher dans chaque fiche la version FR et  la ou les langues alternatives
- Soit ajouter un lien vers la ressource "Opquast" pour éviter la recherche.

Sinon il existe des outils dédiés : https://www.transifex.com/how-it-works/

**Comment by nhoizey** [comment]
Je pencherais pour l'ajout de la VF dans chaque fiche, comme ça on l'aurait direct sous les yeux.

J'ai testé plusieurs outils, dont Transifex, mais ils isolent chaque phrase, qui se retrouve sans contexte, donc c'est finalement moins pratique.

**Comment by okeul** [comment]
@martinsam Je viens d'ajouter la version en Français directement dans les fiches pour que ça soit plus simple ;-)

**Comment by nhoizey** [comment]
Super, merci @okeul !
