### ISSUE TITLE
Utiliser des ID (ou slugs) pour les noms de fichiers ?

### ISSUE THREAD

**Issue by nhoizey** [cleverage/accessibility-steps#3]
Je crains que l'on ai tôt ou tard des soucis avec des noms de fichiers comme celui-ci :

[01 - Use with caution successive div elements whose contents start with -, –, —, \* or •.md](https://github.com/cleverage/accessibility-steps/blob/master/accessibility-second-step/en/01%20-%20Use%20with%20caution%20successive%20div%20elements%20whose%20contents%20start%20with%20-%2C%20%E2%80%93%2C%20%E2%80%94%2C%20*%20or%20%E2%80%A2.md).

**Comment by okeul** [comment]
Bonne idée, ça risque de poser soucis. Comment déterminer les slugs ?

**Comment by borisschapira** [comment]
Pourquoi ne pas garder que les Ids ? On a besoin des noms ?

**Comment by okeul** [comment]
Ca va pas être super parlant une page avec que des ID non ?

**Comment by nhoizey** [comment]
J'ai peur aussi que ça complique si on ne garde que les ID, même si ça évite tout problème de nom évidemment…

**Comment by nhoizey** [comment]
on peut utiliser [le filtre `slugify` de Jekyll](http://jekyllrb.com/docs/templates/#filters) peut-être ?

**Comment by nhoizey** [comment]
Sinon, c'est vrai qu'en mettant juste l'ID comme suggère Boris :
- on s'évite de trimbaler plusieurs noms,
- les fichiers ont le même nom dans toutes les langues,
- ça pourrait permettre de plus facilement faire des liens entre langues.

**Comment by dzc34** [comment]
juste les ID, c'est quand même plus pratique...
après c'est juste un sommaire à générer pour retrouver ses petits...

**Comment by okeul** [comment]
À voir au niveau des contributeurs, si c'est plus simple de partir sur un ID et qu'on arrive à identifier la correspondance ID => intitulé et bien pourquoi pas :-)

**Comment by dzc34** [comment]
c'est surtout pour les liens : ils sont prévisibles... 
plus de copier-coller à faire, juste à connaître le format (...)/14.md

**Comment by nhoizey** [comment]
Allez, un dernier vote pour entériner le choix.

Les noms de fichiers avec juste l'ID ?
- Pour : 👍
- Contre : 👎

**Comment by borisschapira** [comment]
Ah ouais, gros débat.

**Comment by nhoizey** [comment]
Ok, 4 pour et 0 contre, on change.

Comment on gère, pour les PR en cours, j'ai pas trop l'habitude de renommer des fichiers en cours de route.
